/*
 * Enigma API
 * API for the Enigma project. - Base URL: http://localhost:8080 - No authentication or authorization required - All endpoints are prefixed with `/enigma` 
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;

import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;

import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import org.openapitools.client.JSON;

/**
 * Non-verbose mode (false or default) – compact only
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-02-13T22:14:46.832098+02:00[Asia/Jerusalem]", comments = "Generator version: 7.7.0")
public class GetCurrentMachineStatus200ResponseOneOf1 {
  public static final String SERIALIZED_NAME_TOTAL_ROTORS = "totalRotors";
  @SerializedName(SERIALIZED_NAME_TOTAL_ROTORS)
  private Integer totalRotors;

  public static final String SERIALIZED_NAME_TOTAL_REFLECTORS = "totalReflectors";
  @SerializedName(SERIALIZED_NAME_TOTAL_REFLECTORS)
  private Integer totalReflectors;

  public static final String SERIALIZED_NAME_TOTAL_PROCESSED_MESSAGES = "totalProcessedMessages";
  @SerializedName(SERIALIZED_NAME_TOTAL_PROCESSED_MESSAGES)
  private Integer totalProcessedMessages;

  public static final String SERIALIZED_NAME_ORIGINAL_CODE_COMPACT = "originalCodeCompact";
  @SerializedName(SERIALIZED_NAME_ORIGINAL_CODE_COMPACT)
  private String originalCodeCompact;

  public static final String SERIALIZED_NAME_CURRENT_ROTORS_POSITION_COMPACT = "currentRotorsPositionCompact";
  @SerializedName(SERIALIZED_NAME_CURRENT_ROTORS_POSITION_COMPACT)
  private String currentRotorsPositionCompact;

  public GetCurrentMachineStatus200ResponseOneOf1() {
  }

  public GetCurrentMachineStatus200ResponseOneOf1 totalRotors(Integer totalRotors) {
    this.totalRotors = totalRotors;
    return this;
  }

  /**
   * Get totalRotors
   * @return totalRotors
   */
  @javax.annotation.Nonnull
  public Integer getTotalRotors() {
    return totalRotors;
  }

  public void setTotalRotors(Integer totalRotors) {
    this.totalRotors = totalRotors;
  }


  public GetCurrentMachineStatus200ResponseOneOf1 totalReflectors(Integer totalReflectors) {
    this.totalReflectors = totalReflectors;
    return this;
  }

  /**
   * Get totalReflectors
   * @return totalReflectors
   */
  @javax.annotation.Nonnull
  public Integer getTotalReflectors() {
    return totalReflectors;
  }

  public void setTotalReflectors(Integer totalReflectors) {
    this.totalReflectors = totalReflectors;
  }


  public GetCurrentMachineStatus200ResponseOneOf1 totalProcessedMessages(Integer totalProcessedMessages) {
    this.totalProcessedMessages = totalProcessedMessages;
    return this;
  }

  /**
   * Get totalProcessedMessages
   * @return totalProcessedMessages
   */
  @javax.annotation.Nonnull
  public Integer getTotalProcessedMessages() {
    return totalProcessedMessages;
  }

  public void setTotalProcessedMessages(Integer totalProcessedMessages) {
    this.totalProcessedMessages = totalProcessedMessages;
  }


  public GetCurrentMachineStatus200ResponseOneOf1 originalCodeCompact(String originalCodeCompact) {
    this.originalCodeCompact = originalCodeCompact;
    return this;
  }

  /**
   * Compact string representation of the original code.
   * @return originalCodeCompact
   */
  @javax.annotation.Nonnull
  public String getOriginalCodeCompact() {
    return originalCodeCompact;
  }

  public void setOriginalCodeCompact(String originalCodeCompact) {
    this.originalCodeCompact = originalCodeCompact;
  }


  public GetCurrentMachineStatus200ResponseOneOf1 currentRotorsPositionCompact(String currentRotorsPositionCompact) {
    this.currentRotorsPositionCompact = currentRotorsPositionCompact;
    return this;
  }

  /**
   * Compact string representation of the current rotors position.
   * @return currentRotorsPositionCompact
   */
  @javax.annotation.Nonnull
  public String getCurrentRotorsPositionCompact() {
    return currentRotorsPositionCompact;
  }

  public void setCurrentRotorsPositionCompact(String currentRotorsPositionCompact) {
    this.currentRotorsPositionCompact = currentRotorsPositionCompact;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GetCurrentMachineStatus200ResponseOneOf1 getCurrentMachineStatus200ResponseOneOf1 = (GetCurrentMachineStatus200ResponseOneOf1) o;
    return Objects.equals(this.totalRotors, getCurrentMachineStatus200ResponseOneOf1.totalRotors) &&
        Objects.equals(this.totalReflectors, getCurrentMachineStatus200ResponseOneOf1.totalReflectors) &&
        Objects.equals(this.totalProcessedMessages, getCurrentMachineStatus200ResponseOneOf1.totalProcessedMessages) &&
        Objects.equals(this.originalCodeCompact, getCurrentMachineStatus200ResponseOneOf1.originalCodeCompact) &&
        Objects.equals(this.currentRotorsPositionCompact, getCurrentMachineStatus200ResponseOneOf1.currentRotorsPositionCompact);
  }

  @Override
  public int hashCode() {
    return Objects.hash(totalRotors, totalReflectors, totalProcessedMessages, originalCodeCompact, currentRotorsPositionCompact);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GetCurrentMachineStatus200ResponseOneOf1 {\n");
    sb.append("    totalRotors: ").append(toIndentedString(totalRotors)).append("\n");
    sb.append("    totalReflectors: ").append(toIndentedString(totalReflectors)).append("\n");
    sb.append("    totalProcessedMessages: ").append(toIndentedString(totalProcessedMessages)).append("\n");
    sb.append("    originalCodeCompact: ").append(toIndentedString(originalCodeCompact)).append("\n");
    sb.append("    currentRotorsPositionCompact: ").append(toIndentedString(currentRotorsPositionCompact)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("totalRotors");
    openapiFields.add("totalReflectors");
    openapiFields.add("totalProcessedMessages");
    openapiFields.add("originalCodeCompact");
    openapiFields.add("currentRotorsPositionCompact");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("totalRotors");
    openapiRequiredFields.add("totalReflectors");
    openapiRequiredFields.add("totalProcessedMessages");
    openapiRequiredFields.add("originalCodeCompact");
    openapiRequiredFields.add("currentRotorsPositionCompact");
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to GetCurrentMachineStatus200ResponseOneOf1
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!GetCurrentMachineStatus200ResponseOneOf1.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in GetCurrentMachineStatus200ResponseOneOf1 is not found in the empty JSON string", GetCurrentMachineStatus200ResponseOneOf1.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!GetCurrentMachineStatus200ResponseOneOf1.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `GetCurrentMachineStatus200ResponseOneOf1` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : GetCurrentMachineStatus200ResponseOneOf1.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if (!jsonObj.get("originalCodeCompact").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `originalCodeCompact` to be a primitive type in the JSON string but got `%s`", jsonObj.get("originalCodeCompact").toString()));
      }
      if (!jsonObj.get("currentRotorsPositionCompact").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `currentRotorsPositionCompact` to be a primitive type in the JSON string but got `%s`", jsonObj.get("currentRotorsPositionCompact").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!GetCurrentMachineStatus200ResponseOneOf1.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'GetCurrentMachineStatus200ResponseOneOf1' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<GetCurrentMachineStatus200ResponseOneOf1> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(GetCurrentMachineStatus200ResponseOneOf1.class));

       return (TypeAdapter<T>) new TypeAdapter<GetCurrentMachineStatus200ResponseOneOf1>() {
           @Override
           public void write(JsonWriter out, GetCurrentMachineStatus200ResponseOneOf1 value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public GetCurrentMachineStatus200ResponseOneOf1 read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of GetCurrentMachineStatus200ResponseOneOf1 given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of GetCurrentMachineStatus200ResponseOneOf1
   * @throws IOException if the JSON string is invalid with respect to GetCurrentMachineStatus200ResponseOneOf1
   */
  public static GetCurrentMachineStatus200ResponseOneOf1 fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, GetCurrentMachineStatus200ResponseOneOf1.class);
  }

  /**
   * Convert an instance of GetCurrentMachineStatus200ResponseOneOf1 to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

