/*
 * Enigma API
 * API for the Enigma project. - Base URL: http://localhost:8080 - No authentication or authorization required - All endpoints are prefixed with `/enigma` 
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;

import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;

import java.io.IOException;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import org.openapitools.client.JSON;

/**
 * PlugConnection
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-02-13T22:14:46.832098+02:00[Asia/Jerusalem]", comments = "Generator version: 7.7.0")
public class PlugConnection {
  public static final String SERIALIZED_NAME_PLUG1 = "plug1";
  @SerializedName(SERIALIZED_NAME_PLUG1)
  private String plug1;

  public static final String SERIALIZED_NAME_PLUG2 = "plug2";
  @SerializedName(SERIALIZED_NAME_PLUG2)
  private String plug2;

  public PlugConnection() {
  }

  public PlugConnection plug1(String plug1) {
    this.plug1 = plug1;
    return this;
  }

  /**
   * First plug endpoint.
   * @return plug1
   */
  @javax.annotation.Nonnull
  public String getPlug1() {
    return plug1;
  }

  public void setPlug1(String plug1) {
    this.plug1 = plug1;
  }


  public PlugConnection plug2(String plug2) {
    this.plug2 = plug2;
    return this;
  }

  /**
   * Second plug endpoint.
   * @return plug2
   */
  @javax.annotation.Nonnull
  public String getPlug2() {
    return plug2;
  }

  public void setPlug2(String plug2) {
    this.plug2 = plug2;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PlugConnection plugConnection = (PlugConnection) o;
    return Objects.equals(this.plug1, plugConnection.plug1) &&
        Objects.equals(this.plug2, plugConnection.plug2);
  }

  @Override
  public int hashCode() {
    return Objects.hash(plug1, plug2);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PlugConnection {\n");
    sb.append("    plug1: ").append(toIndentedString(plug1)).append("\n");
    sb.append("    plug2: ").append(toIndentedString(plug2)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("plug1");
    openapiFields.add("plug2");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("plug1");
    openapiRequiredFields.add("plug2");
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to PlugConnection
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!PlugConnection.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in PlugConnection is not found in the empty JSON string", PlugConnection.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!PlugConnection.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `PlugConnection` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : PlugConnection.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if (!jsonObj.get("plug1").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `plug1` to be a primitive type in the JSON string but got `%s`", jsonObj.get("plug1").toString()));
      }
      if (!jsonObj.get("plug2").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `plug2` to be a primitive type in the JSON string but got `%s`", jsonObj.get("plug2").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!PlugConnection.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'PlugConnection' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<PlugConnection> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(PlugConnection.class));

       return (TypeAdapter<T>) new TypeAdapter<PlugConnection>() {
           @Override
           public void write(JsonWriter out, PlugConnection value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public PlugConnection read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of PlugConnection given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of PlugConnection
   * @throws IOException if the JSON string is invalid with respect to PlugConnection
   */
  public static PlugConnection fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, PlugConnection.class);
  }

  /**
   * Convert an instance of PlugConnection to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

