/*
 * Enigma API
 * API for the Enigma project. - Base URL: http://localhost:8080 - No authentication or authorization required - All endpoints are prefixed with `/enigma` 
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;

import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;

import java.io.IOException;
import java.math.BigDecimal;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonWriter;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import org.openapitools.client.JSON;

/**
 * RotorSelectionWithNotch
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-02-13T22:14:46.832098+02:00[Asia/Jerusalem]", comments = "Generator version: 7.7.0")
public class RotorSelectionWithNotch {
  public static final String SERIALIZED_NAME_ROTOR_NUMBER = "rotorNumber";
  @SerializedName(SERIALIZED_NAME_ROTOR_NUMBER)
  private Integer rotorNumber;

  public static final String SERIALIZED_NAME_ROTOR_POSITION = "rotorPosition";
  @SerializedName(SERIALIZED_NAME_ROTOR_POSITION)
  private String rotorPosition;

  public static final String SERIALIZED_NAME_NOTCH_DISTANCE = "notchDistance";
  @SerializedName(SERIALIZED_NAME_NOTCH_DISTANCE)
  private BigDecimal notchDistance;

  public RotorSelectionWithNotch() {
  }

  public RotorSelectionWithNotch rotorNumber(Integer rotorNumber) {
    this.rotorNumber = rotorNumber;
    return this;
  }

  /**
   * Rotor identifier/ordinal in the machine catalog.
   * @return rotorNumber
   */
  @javax.annotation.Nonnull
  public Integer getRotorNumber() {
    return rotorNumber;
  }

  public void setRotorNumber(Integer rotorNumber) {
    this.rotorNumber = rotorNumber;
  }


  public RotorSelectionWithNotch rotorPosition(String rotorPosition) {
    this.rotorPosition = rotorPosition;
    return this;
  }

  /**
   * Single-character initial position for this rotor.
   * @return rotorPosition
   */
  @javax.annotation.Nonnull
  public String getRotorPosition() {
    return rotorPosition;
  }

  public void setRotorPosition(String rotorPosition) {
    this.rotorPosition = rotorPosition;
  }


  public RotorSelectionWithNotch notchDistance(BigDecimal notchDistance) {
    this.notchDistance = notchDistance;
    return this;
  }

  /**
   * Distance (in steps) from the current rotor position to the notch.
   * @return notchDistance
   */
  @javax.annotation.Nonnull
  public BigDecimal getNotchDistance() {
    return notchDistance;
  }

  public void setNotchDistance(BigDecimal notchDistance) {
    this.notchDistance = notchDistance;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RotorSelectionWithNotch rotorSelectionWithNotch = (RotorSelectionWithNotch) o;
    return Objects.equals(this.rotorNumber, rotorSelectionWithNotch.rotorNumber) &&
        Objects.equals(this.rotorPosition, rotorSelectionWithNotch.rotorPosition) &&
        Objects.equals(this.notchDistance, rotorSelectionWithNotch.notchDistance);
  }

  @Override
  public int hashCode() {
    return Objects.hash(rotorNumber, rotorPosition, notchDistance);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RotorSelectionWithNotch {\n");
    sb.append("    rotorNumber: ").append(toIndentedString(rotorNumber)).append("\n");
    sb.append("    rotorPosition: ").append(toIndentedString(rotorPosition)).append("\n");
    sb.append("    notchDistance: ").append(toIndentedString(notchDistance)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("rotorNumber");
    openapiFields.add("rotorPosition");
    openapiFields.add("notchDistance");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("rotorNumber");
    openapiRequiredFields.add("rotorPosition");
    openapiRequiredFields.add("notchDistance");
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to RotorSelectionWithNotch
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!RotorSelectionWithNotch.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in RotorSelectionWithNotch is not found in the empty JSON string", RotorSelectionWithNotch.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!RotorSelectionWithNotch.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `RotorSelectionWithNotch` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : RotorSelectionWithNotch.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if (!jsonObj.get("rotorPosition").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `rotorPosition` to be a primitive type in the JSON string but got `%s`", jsonObj.get("rotorPosition").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!RotorSelectionWithNotch.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'RotorSelectionWithNotch' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<RotorSelectionWithNotch> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(RotorSelectionWithNotch.class));

       return (TypeAdapter<T>) new TypeAdapter<RotorSelectionWithNotch>() {
           @Override
           public void write(JsonWriter out, RotorSelectionWithNotch value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public RotorSelectionWithNotch read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of RotorSelectionWithNotch given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of RotorSelectionWithNotch
   * @throws IOException if the JSON string is invalid with respect to RotorSelectionWithNotch
   */
  public static RotorSelectionWithNotch fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, RotorSelectionWithNotch.class);
  }

  /**
   * Convert an instance of RotorSelectionWithNotch to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

