/*
 * Enigma API
 * API for the Enigma project. - Base URL: http://localhost:8080 - No authentication or authorization required - All endpoints are prefixed with `/enigma` 
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import org.openapitools.client.ApiException;
import org.openapitools.client.model.CreateSession200Response;
import org.openapitools.client.model.CreateSession409Response;
import org.openapitools.client.model.CreateSessionRequest;
import org.openapitools.client.model.DeleteSession404Response;
import org.openapitools.client.model.EnigmaManualConfigRequest;
import java.io.File;
import org.openapitools.client.model.GetCurrentMachineStatus200Response;
import org.openapitools.client.model.GetMachineHistory400Response;
import org.openapitools.client.model.HistoryEntry;
import org.openapitools.client.model.LoadMachineFromXml200Response;
import org.openapitools.client.model.LoadMachineFromXml400Response;
import org.openapitools.client.model.ProcessInput200Response;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for EnigmaApi
 */
@Disabled
public class EnigmaApiTest {

    private final EnigmaApi api = new EnigmaApi();

    /**
     * Create a session for a machine
     *
     * Creates a new session for the given machine name. The machine name must match a machine previously loaded into the system. 
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void createSessionTest() throws ApiException {
        CreateSessionRequest createSessionRequest = null;
        CreateSession200Response response = api.createSession(createSessionRequest);
        // TODO: test validations
    }

    /**
     * Delete a session
     *
     * Deletes the session identified by the given sessionID.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void deleteSessionTest() throws ApiException {
        String sessionID = null;
        api.deleteSession(sessionID);
        // TODO: test validations
    }

    /**
     * Get current machine status
     *
     * Returns the current status and configuration details of the loaded Enigma machine.  The optional &#x60;verbose&#x60; query parameter controls how much detail is returned: - When &#x60;verbose&#x3D;true&#x60;, the response includes &#x60;originalCode&#x60; and &#x60;currentRotorsPosition&#x60;. - When &#x60;verbose&#x3D;false&#x60; or not provided (default), these attributes are omitted. 
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getCurrentMachineStatusTest() throws ApiException {
        String sessionID = null;
        Boolean verbose = null;
        GetCurrentMachineStatus200Response response = api.getCurrentMachineStatus(sessionID, verbose);
        // TODO: test validations
    }

    /**
     * Get machine history
     *
     * Returns processing history based on either a specific session or an entire machine.  Exactly **one** of the following query parameters must be provided: - &#x60;sessionID&#x60; – returns history for a single session - &#x60;machineName&#x60; – returns history across all sessions of the given machine  Providing both parameters or none at all is invalid. 
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getMachineHistoryTest() throws ApiException {
        String sessionID = null;
        String machineName = null;
        Map<String, List<HistoryEntry>> response = api.getMachineHistory(sessionID, machineName);
        // TODO: test validations
    }

    /**
     * Load machine configuration from an XML file
     *
     * Upload an XML file representing the Enigma machine configuration. The server parses and loads the machine definition. 
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void loadMachineFromXmlTest() throws ApiException {
        File _file = null;
        LoadMachineFromXml200Response response = api.loadMachineFromXml(_file);
        // TODO: test validations
    }

    /**
     * Process input through the Enigma machine
     *
     * Encrypts/decrypts the provided input using the current machine state. This operation advances rotor positions (stateful). 
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void processInputTest() throws ApiException {
        String input = null;
        ProcessInput200Response response = api.processInput(input);
        // TODO: test validations
    }

    /**
     * Reset to original code
     *
     * Resets the current machine configuration back to the original loaded code and returns it.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void resetToOriginalCodeTest() throws ApiException {
        String sessionID = null;
        String response = api.resetToOriginalCode(sessionID);
        // TODO: test validations
    }

    /**
     * Automatic code setup
     *
     * Automatically generates and applies a random valid Enigma code setup.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void setAutomaticCodeSetupTest() throws ApiException {
        String sessionID = null;
        String response = api.setAutomaticCodeSetup(sessionID);
        // TODO: test validations
    }

    /**
     * Manual code selection
     *
     * Manually set the machine&#39;s secret code rotor selection and positions, reflector, and optional plugboard connections.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void setManualCodeSelectionTest() throws ApiException {
        EnigmaManualConfigRequest enigmaManualConfigRequest = null;
        String response = api.setManualCodeSelection(enigmaManualConfigRequest);
        // TODO: test validations
    }

}
