/*
 * Enigma API
 * API for the Enigma project. - Base URL: http://localhost:8080 - No authentication or authorization required - All endpoints are prefixed with `/enigma` 
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import org.openapitools.client.ApiCallback;
import org.openapitools.client.ApiClient;
import org.openapitools.client.ApiException;
import org.openapitools.client.ApiResponse;
import org.openapitools.client.Configuration;
import org.openapitools.client.Pair;
import org.openapitools.client.ProgressRequestBody;
import org.openapitools.client.ProgressResponseBody;

import com.google.gson.reflect.TypeToken;

import java.io.IOException;


import org.openapitools.client.model.CreateSession200Response;
import org.openapitools.client.model.CreateSession409Response;
import org.openapitools.client.model.CreateSessionRequest;
import org.openapitools.client.model.DeleteSession404Response;
import org.openapitools.client.model.EnigmaManualConfigRequest;
import java.io.File;
import org.openapitools.client.model.GetCurrentMachineStatus200Response;
import org.openapitools.client.model.GetMachineHistory400Response;
import org.openapitools.client.model.HistoryEntry;
import org.openapitools.client.model.LoadMachineFromXml200Response;
import org.openapitools.client.model.LoadMachineFromXml400Response;
import org.openapitools.client.model.ProcessInput200Response;

import java.lang.reflect.Type;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class EnigmaApi {
    private ApiClient localVarApiClient;
    private int localHostIndex;
    private String localCustomBaseUrl;

    public EnigmaApi() {
        this(Configuration.getDefaultApiClient());
    }

    public EnigmaApi(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public ApiClient getApiClient() {
        return localVarApiClient;
    }

    public void setApiClient(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public int getHostIndex() {
        return localHostIndex;
    }

    public void setHostIndex(int hostIndex) {
        this.localHostIndex = hostIndex;
    }

    public String getCustomBaseUrl() {
        return localCustomBaseUrl;
    }

    public void setCustomBaseUrl(String customBaseUrl) {
        this.localCustomBaseUrl = customBaseUrl;
    }

    /**
     * Build call for createSession
     * @param createSessionRequest  (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Session was created successfully. </td><td>  -  </td></tr>
        <tr><td> 409 </td><td> Conflict - unknown machine name </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call createSessionCall(CreateSessionRequest createSessionRequest, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = createSessionRequest;

        // create path and map variables
        String localVarPath = "/enigma/session";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            "application/json"
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] {  };
        return localVarApiClient.buildCall(basePath, localVarPath, "POST", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call createSessionValidateBeforeCall(CreateSessionRequest createSessionRequest, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'createSessionRequest' is set
        if (createSessionRequest == null) {
            throw new ApiException("Missing the required parameter 'createSessionRequest' when calling createSession(Async)");
        }

        return createSessionCall(createSessionRequest, _callback);

    }

    /**
     * Create a session for a machine
     * Creates a new session for the given machine name. The machine name must match a machine previously loaded into the system. 
     * @param createSessionRequest  (required)
     * @return CreateSession200Response
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Session was created successfully. </td><td>  -  </td></tr>
        <tr><td> 409 </td><td> Conflict - unknown machine name </td><td>  -  </td></tr>
     </table>
     */
    public CreateSession200Response createSession(CreateSessionRequest createSessionRequest) throws ApiException {
        ApiResponse<CreateSession200Response> localVarResp = createSessionWithHttpInfo(createSessionRequest);
        return localVarResp.getData();
    }

    /**
     * Create a session for a machine
     * Creates a new session for the given machine name. The machine name must match a machine previously loaded into the system. 
     * @param createSessionRequest  (required)
     * @return ApiResponse&lt;CreateSession200Response&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Session was created successfully. </td><td>  -  </td></tr>
        <tr><td> 409 </td><td> Conflict - unknown machine name </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<CreateSession200Response> createSessionWithHttpInfo(CreateSessionRequest createSessionRequest) throws ApiException {
        okhttp3.Call localVarCall = createSessionValidateBeforeCall(createSessionRequest, null);
        Type localVarReturnType = new TypeToken<CreateSession200Response>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Create a session for a machine (asynchronously)
     * Creates a new session for the given machine name. The machine name must match a machine previously loaded into the system. 
     * @param createSessionRequest  (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Session was created successfully. </td><td>  -  </td></tr>
        <tr><td> 409 </td><td> Conflict - unknown machine name </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call createSessionAsync(CreateSessionRequest createSessionRequest, final ApiCallback<CreateSession200Response> _callback) throws ApiException {

        okhttp3.Call localVarCall = createSessionValidateBeforeCall(createSessionRequest, _callback);
        Type localVarReturnType = new TypeToken<CreateSession200Response>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for deleteSession
     * @param sessionID The session identifier to delete. (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 204 </td><td> Session deleted successfully. </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Session not found. </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call deleteSessionCall(String sessionID, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/enigma/session";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        if (sessionID != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("sessionID", sessionID));
        }

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] {  };
        return localVarApiClient.buildCall(basePath, localVarPath, "DELETE", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call deleteSessionValidateBeforeCall(String sessionID, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'sessionID' is set
        if (sessionID == null) {
            throw new ApiException("Missing the required parameter 'sessionID' when calling deleteSession(Async)");
        }

        return deleteSessionCall(sessionID, _callback);

    }

    /**
     * Delete a session
     * Deletes the session identified by the given sessionID.
     * @param sessionID The session identifier to delete. (required)
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 204 </td><td> Session deleted successfully. </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Session not found. </td><td>  -  </td></tr>
     </table>
     */
    public void deleteSession(String sessionID) throws ApiException {
        deleteSessionWithHttpInfo(sessionID);
    }

    /**
     * Delete a session
     * Deletes the session identified by the given sessionID.
     * @param sessionID The session identifier to delete. (required)
     * @return ApiResponse&lt;Void&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 204 </td><td> Session deleted successfully. </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Session not found. </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<Void> deleteSessionWithHttpInfo(String sessionID) throws ApiException {
        okhttp3.Call localVarCall = deleteSessionValidateBeforeCall(sessionID, null);
        return localVarApiClient.execute(localVarCall);
    }

    /**
     * Delete a session (asynchronously)
     * Deletes the session identified by the given sessionID.
     * @param sessionID The session identifier to delete. (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 204 </td><td> Session deleted successfully. </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Session not found. </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call deleteSessionAsync(String sessionID, final ApiCallback<Void> _callback) throws ApiException {

        okhttp3.Call localVarCall = deleteSessionValidateBeforeCall(sessionID, _callback);
        localVarApiClient.executeAsync(localVarCall, _callback);
        return localVarCall;
    }
    /**
     * Build call for getCurrentMachineStatus
     * @param sessionID The active session identifier. (required)
     * @param verbose If true, include detailed code structures (&#x60;originalCode&#x60; and &#x60;currentRotorsPosition&#x60;) in the response. Default: false.  (optional, default to false)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Current configuration </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call getCurrentMachineStatusCall(String sessionID, Boolean verbose, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/enigma/config";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        if (sessionID != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("sessionID", sessionID));
        }

        if (verbose != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("verbose", verbose));
        }

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] {  };
        return localVarApiClient.buildCall(basePath, localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call getCurrentMachineStatusValidateBeforeCall(String sessionID, Boolean verbose, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'sessionID' is set
        if (sessionID == null) {
            throw new ApiException("Missing the required parameter 'sessionID' when calling getCurrentMachineStatus(Async)");
        }

        return getCurrentMachineStatusCall(sessionID, verbose, _callback);

    }

    /**
     * Get current machine status
     * Returns the current status and configuration details of the loaded Enigma machine.  The optional &#x60;verbose&#x60; query parameter controls how much detail is returned: - When &#x60;verbose&#x3D;true&#x60;, the response includes &#x60;originalCode&#x60; and &#x60;currentRotorsPosition&#x60;. - When &#x60;verbose&#x3D;false&#x60; or not provided (default), these attributes are omitted. 
     * @param sessionID The active session identifier. (required)
     * @param verbose If true, include detailed code structures (&#x60;originalCode&#x60; and &#x60;currentRotorsPosition&#x60;) in the response. Default: false.  (optional, default to false)
     * @return GetCurrentMachineStatus200Response
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Current configuration </td><td>  -  </td></tr>
     </table>
     */
    public GetCurrentMachineStatus200Response getCurrentMachineStatus(String sessionID, Boolean verbose) throws ApiException {
        ApiResponse<GetCurrentMachineStatus200Response> localVarResp = getCurrentMachineStatusWithHttpInfo(sessionID, verbose);
        return localVarResp.getData();
    }

    /**
     * Get current machine status
     * Returns the current status and configuration details of the loaded Enigma machine.  The optional &#x60;verbose&#x60; query parameter controls how much detail is returned: - When &#x60;verbose&#x3D;true&#x60;, the response includes &#x60;originalCode&#x60; and &#x60;currentRotorsPosition&#x60;. - When &#x60;verbose&#x3D;false&#x60; or not provided (default), these attributes are omitted. 
     * @param sessionID The active session identifier. (required)
     * @param verbose If true, include detailed code structures (&#x60;originalCode&#x60; and &#x60;currentRotorsPosition&#x60;) in the response. Default: false.  (optional, default to false)
     * @return ApiResponse&lt;GetCurrentMachineStatus200Response&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Current configuration </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<GetCurrentMachineStatus200Response> getCurrentMachineStatusWithHttpInfo(String sessionID, Boolean verbose) throws ApiException {
        okhttp3.Call localVarCall = getCurrentMachineStatusValidateBeforeCall(sessionID, verbose, null);
        Type localVarReturnType = new TypeToken<GetCurrentMachineStatus200Response>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Get current machine status (asynchronously)
     * Returns the current status and configuration details of the loaded Enigma machine.  The optional &#x60;verbose&#x60; query parameter controls how much detail is returned: - When &#x60;verbose&#x3D;true&#x60;, the response includes &#x60;originalCode&#x60; and &#x60;currentRotorsPosition&#x60;. - When &#x60;verbose&#x3D;false&#x60; or not provided (default), these attributes are omitted. 
     * @param sessionID The active session identifier. (required)
     * @param verbose If true, include detailed code structures (&#x60;originalCode&#x60; and &#x60;currentRotorsPosition&#x60;) in the response. Default: false.  (optional, default to false)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Current configuration </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call getCurrentMachineStatusAsync(String sessionID, Boolean verbose, final ApiCallback<GetCurrentMachineStatus200Response> _callback) throws ApiException {

        okhttp3.Call localVarCall = getCurrentMachineStatusValidateBeforeCall(sessionID, verbose, _callback);
        Type localVarReturnType = new TypeToken<GetCurrentMachineStatus200Response>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for getMachineHistory
     * @param sessionID Session identifier. When provided, history is returned only for this session.  (optional)
     * @param machineName Machine name. When provided, history is returned across all sessions of this machine.  (optional)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> History grouped by code description </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Invalid request – exactly one query parameter must be provided </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call getMachineHistoryCall(String sessionID, String machineName, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/enigma/history";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        if (sessionID != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("sessionID", sessionID));
        }

        if (machineName != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("machineName", machineName));
        }

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] {  };
        return localVarApiClient.buildCall(basePath, localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call getMachineHistoryValidateBeforeCall(String sessionID, String machineName, final ApiCallback _callback) throws ApiException {
        return getMachineHistoryCall(sessionID, machineName, _callback);

    }

    /**
     * Get machine history
     * Returns processing history based on either a specific session or an entire machine.  Exactly **one** of the following query parameters must be provided: - &#x60;sessionID&#x60; – returns history for a single session - &#x60;machineName&#x60; – returns history across all sessions of the given machine  Providing both parameters or none at all is invalid. 
     * @param sessionID Session identifier. When provided, history is returned only for this session.  (optional)
     * @param machineName Machine name. When provided, history is returned across all sessions of this machine.  (optional)
     * @return Map&lt;String, List&lt;HistoryEntry&gt;&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> History grouped by code description </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Invalid request – exactly one query parameter must be provided </td><td>  -  </td></tr>
     </table>
     */
    public Map<String, List<HistoryEntry>> getMachineHistory(String sessionID, String machineName) throws ApiException {
        ApiResponse<Map<String, List<HistoryEntry>>> localVarResp = getMachineHistoryWithHttpInfo(sessionID, machineName);
        return localVarResp.getData();
    }

    /**
     * Get machine history
     * Returns processing history based on either a specific session or an entire machine.  Exactly **one** of the following query parameters must be provided: - &#x60;sessionID&#x60; – returns history for a single session - &#x60;machineName&#x60; – returns history across all sessions of the given machine  Providing both parameters or none at all is invalid. 
     * @param sessionID Session identifier. When provided, history is returned only for this session.  (optional)
     * @param machineName Machine name. When provided, history is returned across all sessions of this machine.  (optional)
     * @return ApiResponse&lt;Map&lt;String, List&lt;HistoryEntry&gt;&gt;&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> History grouped by code description </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Invalid request – exactly one query parameter must be provided </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<Map<String, List<HistoryEntry>>> getMachineHistoryWithHttpInfo(String sessionID, String machineName) throws ApiException {
        okhttp3.Call localVarCall = getMachineHistoryValidateBeforeCall(sessionID, machineName, null);
        Type localVarReturnType = new TypeToken<Map<String, List<HistoryEntry>>>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Get machine history (asynchronously)
     * Returns processing history based on either a specific session or an entire machine.  Exactly **one** of the following query parameters must be provided: - &#x60;sessionID&#x60; – returns history for a single session - &#x60;machineName&#x60; – returns history across all sessions of the given machine  Providing both parameters or none at all is invalid. 
     * @param sessionID Session identifier. When provided, history is returned only for this session.  (optional)
     * @param machineName Machine name. When provided, history is returned across all sessions of this machine.  (optional)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> History grouped by code description </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Invalid request – exactly one query parameter must be provided </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call getMachineHistoryAsync(String sessionID, String machineName, final ApiCallback<Map<String, List<HistoryEntry>>> _callback) throws ApiException {

        okhttp3.Call localVarCall = getMachineHistoryValidateBeforeCall(sessionID, machineName, _callback);
        Type localVarReturnType = new TypeToken<Map<String, List<HistoryEntry>>>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for loadMachineFromXml
     * @param _file The XML file to upload (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Load result </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Invalid or missing file </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call loadMachineFromXmlCall(File _file, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/enigma/load";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        if (_file != null) {
            localVarFormParams.put("file", _file);
        }

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            "multipart/form-data"
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] {  };
        return localVarApiClient.buildCall(basePath, localVarPath, "POST", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call loadMachineFromXmlValidateBeforeCall(File _file, final ApiCallback _callback) throws ApiException {
        // verify the required parameter '_file' is set
        if (_file == null) {
            throw new ApiException("Missing the required parameter '_file' when calling loadMachineFromXml(Async)");
        }

        return loadMachineFromXmlCall(_file, _callback);

    }

    /**
     * Load machine configuration from an XML file
     * Upload an XML file representing the Enigma machine configuration. The server parses and loads the machine definition. 
     * @param _file The XML file to upload (required)
     * @return LoadMachineFromXml200Response
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Load result </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Invalid or missing file </td><td>  -  </td></tr>
     </table>
     */
    public LoadMachineFromXml200Response loadMachineFromXml(File _file) throws ApiException {
        ApiResponse<LoadMachineFromXml200Response> localVarResp = loadMachineFromXmlWithHttpInfo(_file);
        return localVarResp.getData();
    }

    /**
     * Load machine configuration from an XML file
     * Upload an XML file representing the Enigma machine configuration. The server parses and loads the machine definition. 
     * @param _file The XML file to upload (required)
     * @return ApiResponse&lt;LoadMachineFromXml200Response&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Load result </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Invalid or missing file </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<LoadMachineFromXml200Response> loadMachineFromXmlWithHttpInfo(File _file) throws ApiException {
        okhttp3.Call localVarCall = loadMachineFromXmlValidateBeforeCall(_file, null);
        Type localVarReturnType = new TypeToken<LoadMachineFromXml200Response>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Load machine configuration from an XML file (asynchronously)
     * Upload an XML file representing the Enigma machine configuration. The server parses and loads the machine definition. 
     * @param _file The XML file to upload (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Load result </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Invalid or missing file </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call loadMachineFromXmlAsync(File _file, final ApiCallback<LoadMachineFromXml200Response> _callback) throws ApiException {

        okhttp3.Call localVarCall = loadMachineFromXmlValidateBeforeCall(_file, _callback);
        Type localVarReturnType = new TypeToken<LoadMachineFromXml200Response>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for processInput
     * @param input The text to process. (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Process result </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call processInputCall(String input, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/enigma/process";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        if (input != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("input", input));
        }

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] {  };
        return localVarApiClient.buildCall(basePath, localVarPath, "POST", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call processInputValidateBeforeCall(String input, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'input' is set
        if (input == null) {
            throw new ApiException("Missing the required parameter 'input' when calling processInput(Async)");
        }

        return processInputCall(input, _callback);

    }

    /**
     * Process input through the Enigma machine
     * Encrypts/decrypts the provided input using the current machine state. This operation advances rotor positions (stateful). 
     * @param input The text to process. (required)
     * @return ProcessInput200Response
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Process result </td><td>  -  </td></tr>
     </table>
     */
    public ProcessInput200Response processInput(String input) throws ApiException {
        ApiResponse<ProcessInput200Response> localVarResp = processInputWithHttpInfo(input);
        return localVarResp.getData();
    }

    /**
     * Process input through the Enigma machine
     * Encrypts/decrypts the provided input using the current machine state. This operation advances rotor positions (stateful). 
     * @param input The text to process. (required)
     * @return ApiResponse&lt;ProcessInput200Response&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Process result </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<ProcessInput200Response> processInputWithHttpInfo(String input) throws ApiException {
        okhttp3.Call localVarCall = processInputValidateBeforeCall(input, null);
        Type localVarReturnType = new TypeToken<ProcessInput200Response>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Process input through the Enigma machine (asynchronously)
     * Encrypts/decrypts the provided input using the current machine state. This operation advances rotor positions (stateful). 
     * @param input The text to process. (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Process result </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call processInputAsync(String input, final ApiCallback<ProcessInput200Response> _callback) throws ApiException {

        okhttp3.Call localVarCall = processInputValidateBeforeCall(input, _callback);
        Type localVarReturnType = new TypeToken<ProcessInput200Response>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for resetToOriginalCode
     * @param sessionID The active session identifier. (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Original code after reset </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call resetToOriginalCodeCall(String sessionID, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/enigma/config/reset";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        if (sessionID != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("sessionID", sessionID));
        }

        final String[] localVarAccepts = {
            "text/plain"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] {  };
        return localVarApiClient.buildCall(basePath, localVarPath, "PUT", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call resetToOriginalCodeValidateBeforeCall(String sessionID, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'sessionID' is set
        if (sessionID == null) {
            throw new ApiException("Missing the required parameter 'sessionID' when calling resetToOriginalCode(Async)");
        }

        return resetToOriginalCodeCall(sessionID, _callback);

    }

    /**
     * Reset to original code
     * Resets the current machine configuration back to the original loaded code and returns it.
     * @param sessionID The active session identifier. (required)
     * @return String
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Original code after reset </td><td>  -  </td></tr>
     </table>
     */
    public String resetToOriginalCode(String sessionID) throws ApiException {
        ApiResponse<String> localVarResp = resetToOriginalCodeWithHttpInfo(sessionID);
        return localVarResp.getData();
    }

    /**
     * Reset to original code
     * Resets the current machine configuration back to the original loaded code and returns it.
     * @param sessionID The active session identifier. (required)
     * @return ApiResponse&lt;String&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Original code after reset </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<String> resetToOriginalCodeWithHttpInfo(String sessionID) throws ApiException {
        okhttp3.Call localVarCall = resetToOriginalCodeValidateBeforeCall(sessionID, null);
        Type localVarReturnType = new TypeToken<String>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Reset to original code (asynchronously)
     * Resets the current machine configuration back to the original loaded code and returns it.
     * @param sessionID The active session identifier. (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Original code after reset </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call resetToOriginalCodeAsync(String sessionID, final ApiCallback<String> _callback) throws ApiException {

        okhttp3.Call localVarCall = resetToOriginalCodeValidateBeforeCall(sessionID, _callback);
        Type localVarReturnType = new TypeToken<String>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for setAutomaticCodeSetup
     * @param sessionID The active session identifier. (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Operation result as a plain string </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call setAutomaticCodeSetupCall(String sessionID, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/enigma/config/automatic";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        if (sessionID != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("sessionID", sessionID));
        }

        final String[] localVarAccepts = {
            "text/plain"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] {  };
        return localVarApiClient.buildCall(basePath, localVarPath, "PUT", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call setAutomaticCodeSetupValidateBeforeCall(String sessionID, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'sessionID' is set
        if (sessionID == null) {
            throw new ApiException("Missing the required parameter 'sessionID' when calling setAutomaticCodeSetup(Async)");
        }

        return setAutomaticCodeSetupCall(sessionID, _callback);

    }

    /**
     * Automatic code setup
     * Automatically generates and applies a random valid Enigma code setup.
     * @param sessionID The active session identifier. (required)
     * @return String
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Operation result as a plain string </td><td>  -  </td></tr>
     </table>
     */
    public String setAutomaticCodeSetup(String sessionID) throws ApiException {
        ApiResponse<String> localVarResp = setAutomaticCodeSetupWithHttpInfo(sessionID);
        return localVarResp.getData();
    }

    /**
     * Automatic code setup
     * Automatically generates and applies a random valid Enigma code setup.
     * @param sessionID The active session identifier. (required)
     * @return ApiResponse&lt;String&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Operation result as a plain string </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<String> setAutomaticCodeSetupWithHttpInfo(String sessionID) throws ApiException {
        okhttp3.Call localVarCall = setAutomaticCodeSetupValidateBeforeCall(sessionID, null);
        Type localVarReturnType = new TypeToken<String>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Automatic code setup (asynchronously)
     * Automatically generates and applies a random valid Enigma code setup.
     * @param sessionID The active session identifier. (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Operation result as a plain string </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call setAutomaticCodeSetupAsync(String sessionID, final ApiCallback<String> _callback) throws ApiException {

        okhttp3.Call localVarCall = setAutomaticCodeSetupValidateBeforeCall(sessionID, _callback);
        Type localVarReturnType = new TypeToken<String>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for setManualCodeSelection
     * @param enigmaManualConfigRequest  (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Operation result as a plain string </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call setManualCodeSelectionCall(EnigmaManualConfigRequest enigmaManualConfigRequest, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = enigmaManualConfigRequest;

        // create path and map variables
        String localVarPath = "/enigma/config/manual";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "text/plain"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            "application/json"
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] {  };
        return localVarApiClient.buildCall(basePath, localVarPath, "PUT", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call setManualCodeSelectionValidateBeforeCall(EnigmaManualConfigRequest enigmaManualConfigRequest, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'enigmaManualConfigRequest' is set
        if (enigmaManualConfigRequest == null) {
            throw new ApiException("Missing the required parameter 'enigmaManualConfigRequest' when calling setManualCodeSelection(Async)");
        }

        return setManualCodeSelectionCall(enigmaManualConfigRequest, _callback);

    }

    /**
     * Manual code selection
     * Manually set the machine&#39;s secret code rotor selection and positions, reflector, and optional plugboard connections.
     * @param enigmaManualConfigRequest  (required)
     * @return String
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Operation result as a plain string </td><td>  -  </td></tr>
     </table>
     */
    public String setManualCodeSelection(EnigmaManualConfigRequest enigmaManualConfigRequest) throws ApiException {
        ApiResponse<String> localVarResp = setManualCodeSelectionWithHttpInfo(enigmaManualConfigRequest);
        return localVarResp.getData();
    }

    /**
     * Manual code selection
     * Manually set the machine&#39;s secret code rotor selection and positions, reflector, and optional plugboard connections.
     * @param enigmaManualConfigRequest  (required)
     * @return ApiResponse&lt;String&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Operation result as a plain string </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<String> setManualCodeSelectionWithHttpInfo(EnigmaManualConfigRequest enigmaManualConfigRequest) throws ApiException {
        okhttp3.Call localVarCall = setManualCodeSelectionValidateBeforeCall(enigmaManualConfigRequest, null);
        Type localVarReturnType = new TypeToken<String>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Manual code selection (asynchronously)
     * Manually set the machine&#39;s secret code rotor selection and positions, reflector, and optional plugboard connections.
     * @param enigmaManualConfigRequest  (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Operation result as a plain string </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call setManualCodeSelectionAsync(EnigmaManualConfigRequest enigmaManualConfigRequest, final ApiCallback<String> _callback) throws ApiException {

        okhttp3.Call localVarCall = setManualCodeSelectionValidateBeforeCall(enigmaManualConfigRequest, _callback);
        Type localVarReturnType = new TypeToken<String>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
}
