/*
 * Enigma API
 * API for the Enigma project. - Base URL: http://localhost:8080 - No authentication or authorization required - All endpoints are prefixed with `/enigma` 
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.openapitools.client.model.PlugConnection;
import org.openapitools.client.model.RotorSelectionWithNotch;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for EnigmaCodeStructure
 */
public class EnigmaCodeStructureTest {
    private final EnigmaCodeStructure model = new EnigmaCodeStructure();

    /**
     * Model tests for EnigmaCodeStructure
     */
    @Test
    public void testEnigmaCodeStructure() {
        // TODO: test EnigmaCodeStructure
    }

    /**
     * Test the property 'rotors'
     */
    @Test
    public void rotorsTest() {
        // TODO: test rotors
    }

    /**
     * Test the property 'reflector'
     */
    @Test
    public void reflectorTest() {
        // TODO: test reflector
    }

    /**
     * Test the property 'plugs'
     */
    @Test
    public void plugsTest() {
        // TODO: test plugs
    }

}
