/*
 * Enigma API
 * API for the Enigma project. - Base URL: http://localhost:8080 - No authentication or authorization required - All endpoints are prefixed with `/enigma` 
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.openapitools.client.model.EnigmaCodeStructure;
import org.openapitools.client.model.GetCurrentMachineStatus200ResponseOneOf;
import org.openapitools.client.model.GetCurrentMachineStatus200ResponseOneOf1;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for GetCurrentMachineStatus200Response
 */
public class GetCurrentMachineStatus200ResponseTest {
    private final GetCurrentMachineStatus200Response model = new GetCurrentMachineStatus200Response();

    /**
     * Model tests for GetCurrentMachineStatus200Response
     */
    @Test
    public void testGetCurrentMachineStatus200Response() {
        // TODO: test GetCurrentMachineStatus200Response
    }

    /**
     * Test the property 'totalRotors'
     */
    @Test
    public void totalRotorsTest() {
        // TODO: test totalRotors
    }

    /**
     * Test the property 'totalReflectors'
     */
    @Test
    public void totalReflectorsTest() {
        // TODO: test totalReflectors
    }

    /**
     * Test the property 'totalProcessedMessages'
     */
    @Test
    public void totalProcessedMessagesTest() {
        // TODO: test totalProcessedMessages
    }

    /**
     * Test the property 'originalCode'
     */
    @Test
    public void originalCodeTest() {
        // TODO: test originalCode
    }

    /**
     * Test the property 'currentRotorsPosition'
     */
    @Test
    public void currentRotorsPositionTest() {
        // TODO: test currentRotorsPosition
    }

    /**
     * Test the property 'originalCodeCompact'
     */
    @Test
    public void originalCodeCompactTest() {
        // TODO: test originalCodeCompact
    }

    /**
     * Test the property 'currentRotorsPositionCompact'
     */
    @Test
    public void currentRotorsPositionCompactTest() {
        // TODO: test currentRotorsPositionCompact
    }

}
