/*
 * Enigma API
 * API for the Enigma project. - Base URL: http://localhost:8080 - No authentication or authorization required - All endpoints are prefixed with `/enigma` 
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for LoadMachineFromXml400Response
 */
public class LoadMachineFromXml400ResponseTest {
    private final LoadMachineFromXml400Response model = new LoadMachineFromXml400Response();

    /**
     * Model tests for LoadMachineFromXml400Response
     */
    @Test
    public void testLoadMachineFromXml400Response() {
        // TODO: test LoadMachineFromXml400Response
    }

    /**
     * Test the property 'success'
     */
    @Test
    public void successTest() {
        // TODO: test success
    }

    /**
     * Test the property 'error'
     */
    @Test
    public void errorTest() {
        // TODO: test error
    }

}
