/*
 * Enigma API
 * API for the Enigma project. - Base URL: http://localhost:8080 - No authentication or authorization required - All endpoints are prefixed with `/enigma` 
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for PlugConnection
 */
public class PlugConnectionTest {
    private final PlugConnection model = new PlugConnection();

    /**
     * Model tests for PlugConnection
     */
    @Test
    public void testPlugConnection() {
        // TODO: test PlugConnection
    }

    /**
     * Test the property 'plug1'
     */
    @Test
    public void plug1Test() {
        // TODO: test plug1
    }

    /**
     * Test the property 'plug2'
     */
    @Test
    public void plug2Test() {
        // TODO: test plug2
    }

}
