/*
 * Enigma API
 * API for the Enigma project. - Base URL: http://localhost:8080 - No authentication or authorization required - All endpoints are prefixed with `/enigma` 
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.math.BigDecimal;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for RotorSelectionWithNotch
 */
public class RotorSelectionWithNotchTest {
    private final RotorSelectionWithNotch model = new RotorSelectionWithNotch();

    /**
     * Model tests for RotorSelectionWithNotch
     */
    @Test
    public void testRotorSelectionWithNotch() {
        // TODO: test RotorSelectionWithNotch
    }

    /**
     * Test the property 'rotorNumber'
     */
    @Test
    public void rotorNumberTest() {
        // TODO: test rotorNumber
    }

    /**
     * Test the property 'rotorPosition'
     */
    @Test
    public void rotorPositionTest() {
        // TODO: test rotorPosition
    }

    /**
     * Test the property 'notchDistance'
     */
    @Test
    public void notchDistanceTest() {
        // TODO: test notchDistance
    }

}
